# Generated by Django 5.1.1 on 2025-02-13 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitriosMunicipales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('fecha_pago', models.DateTimeField(verbose_name='Fecha de Pago')),
                ('municipio', models.CharField(max_length=150, verbose_name='Municipio')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], max_length=10, verbose_name='Estado del Pago')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Proveedor')),
                ('tipo', models.CharField(choices=[('Servicio Público', 'Servicio Público'), ('Impuesto', 'Impuesto'), ('Proveedor Privado', 'Proveedor Privado')], max_length=20, verbose_name='Tipo de Proveedor')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Usuario')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Correo Electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('fecha_pago', models.DateTimeField(verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(choices=[('BCP', 'BCP'), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], max_length=15, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Vencido', 'Vencido')], max_length=10, verbose_name='Estado del Pago')),
                ('comprobante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comprobante')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.categoriagasto', verbose_name='Categoría de Gasto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.proveedor', verbose_name='Proveedor')),
            ],
        ),
    ]
