"""
Django settings for Proyecto1 project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&$++lvb4)-c^2id-wuzm_*$kyux4xi7*##p75rv(g-^&rrcvp@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'paginainteractiva.onrender.com',
    'localhost',
    '127.0.0.1'
]

CSRF_TRUSTED_ORIGINS = [
    'https://paginainteractiva.onrender.com'
]
# Application definition
CORS_ALLOW_ALL_ORIGINS = True  # O restringirlo a dominios específicos

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mi_app',
    'aplicacionLogs',
    'django_plotly_dash',
    'channels',
    'myapp',
    'pedidos',
    'dashboardproductos',
    'vehiculos',
    'pagos',  # Agrega el nombre de la nueva app aquí
    'chatbot1',
    "corsheaders",
    'crispy_forms',

]

CRISPY_TEMPLATE_PACK = 'bootstrap4'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'Proyecto1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Proyecto1.wsgi.application'
ASGI_APPLICATION = 'Proyecto1.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#mysql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'lubricentroalex',  # Cambia esto por el nombre de tu base de datos
        'USER': 'root',            # Cambia esto por tu nombre de usuario MySQL
        'PASSWORD': '1234',     # Cambia esto por tu contraseña MySQL
        'HOST': 'localhost',
        #'HOST': 'host.docker.internal',
        #'HOST': 'db',#'HOST': 'localhost',                   # O la dirección de tu servidor de base de datos
        'PORT': '3306',                        # El puerto por defecto de MySQL es 3306
        
    }
}
# local
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'lubricentroalex',  # Cambia esto por el nombre de tu base de datos
#         'USER': 'root',            # Cambia esto por tu nombre de usuario MySQL
#         'PASSWORD': '1234',     # Cambia esto por tu contraseña MySQL
#         'HOST': 'localhost',
#         'PORT': '3306',                        # El puerto por defecto de MySQL es 3306
        
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'lubricentroalex',
#         'USER': 'root',
#         'PASSWORD': 'K6P5RAeT6J4obXN9PBfzJnV86ak0VXy3',
#         'HOST': 'dpg-ctv8cfd6l47c739uebsg-a.oregon-postgres.render.com',  # External Database URL (host)
#         'PORT': '5432',
#     }
# }

# Si usas PyMySQL en lugar de mysqlclient
#import pymysql
#pymysql.install_as_MySQLdb()

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # Tamaño máximo de 5MB


X_FRAME_OPTIONS = 'ALLOWALL'