# Generated by Django 5.1.1 on 2025-02-12 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, help_text='Costo total del pedido', max_digits=10, verbose_name='Costo Total')),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('pagado', 'Pagado')], default='pendiente', help_text='Estado actual del pago', max_length=10, verbose_name='Estado de Pago')),
                ('fecha_pedido', models.DateField(help_text='Ingrese la fecha en que se realizó el pedido', verbose_name='Fecha de Pedido')),
                ('fecha_entrega', models.DateField(help_text='Ingrese la fecha estimada de entrega', verbose_name='Fecha de Entrega')),
                ('descripcion', models.TextField(blank=True, help_text='Ingrese una descripción o comentarios adicionales sobre el pedido', null=True, verbose_name='Descripción del Pedido')),
                ('proveedor', models.ForeignKey(help_text='Seleccione el proveedor de este pedido', on_delete=django.db.models.deletion.CASCADE, to='mi_app.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Ingrese la cantidad de productos solicitados', verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Ingrese el precio unitario del producto', max_digits=10, verbose_name='Precio Unitario')),
                ('producto', models.ForeignKey(help_text='Seleccione el producto', on_delete=django.db.models.deletion.CASCADE, to='mi_app.producto', verbose_name='Producto')),
                ('pedido', models.ForeignKey(help_text='Seleccione el pedido al que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Detalle del Pedido',
                'verbose_name_plural': 'Detalles del Pedido',
                'ordering': ['producto__nombre_producto'],
            },
        ),
    ]
